name: Add Hacktoberfest Labels

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

permissions:
  issues: write
  pull-requests: write

jobs:
  add-labels:
    runs-on: ubuntu-latest

    steps:
      - name: Add Hacktoberfest labels
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            hacktoberfest
            hacktoberfest2026
